### ISSUE TITLE
Wav file support removed

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/age_of_tribes#2]
We need mp3 format now instead of wavs. Let me know if you would like help converting any new sound files to mp3.  Otherwise you'll notice the wav files on age_of_tribes have been replaced by mp3.

Ps: please join the gitter map channel so we can communicate things like this more easily. (as you own multiple maps, I don't have a centralized place to talk to you @FrostionAAA )

**Comment by DanVanAtta** [comment]
close to acknowledge, let me know one way or another if you've any questions/trouble

**Comment by FrostionAAA** [comment]
**“please join the gitter map channel”**
Sorry, I don’t know what you mean. I have found this website; https://gitter.im/home, but I don’t know what to do from here.
**I posted the following on my Star Trek Beta map thread, but I will just post it here also:**
I can see that all the wav have been replaced by mp3s.
However, the sounds.properties are not all dune. It looks like some automatic replacement of .wav with .mp3 has altered the files, but there is a problem. In the cases where there are several possible sound files to be played, only one has its .wav replaced with .mp3, and that is the last .wav in the line of possible sounds to be played.
Example line from the sounds.properties of the Star trek map (but this might be occurring in some of my other maps):
battle_sea_normal_Federation=battle_sea_normal_Federation_1.wav;battle_sea_normal_Federation_2.mp3
Could you rerun the “auto-alteration” of the sounds.properties thing again? This time replacing ALL .wav references?

**Comment by DanVanAtta** [comment]
That's the right website. You actually found it - Join this room:  https://gitter.im/triplea-maps/Project

IF that link does not work:
http://gitter.im/triplea-maps/Project

Sounds.properties should be updated correctly now
